### PR TITLE
Remove deprecated end points under repository app.

### PR DESCRIPTION
**Pull request by ycheng-aa**

### CODE REVIEW

**Comment by bliuredhat** [comment]
look good for me~!

**Comment by lubomir** [comment]
Should the `repos` and `repo-families` be removed as well? How long are they deprecated?

**Comment by ycheng-aa** [comment]
These 2 should also be removed. Thanks. The renaming task is PDC-463. So the APIs should be claimed as deprecated in 0.6.0.

**Comment by bliuredhat** [comment]
:+1:

**Comment by simozhan** [comment]
:+1:

**Pull request closed without merging**
