### PR TITLE
Publish two new message topics.

### PR DESCRIPTION
**Pull request by ralphbean**
Both for imports of new content.  One for 'images' and the other for 'rpms'.

This is ultimately in pursuit of fixing fedora-infra/pdc-updater#10.

### CODE REVIEW

**Comment by lubomir** [comment]
Looks good to me.

You might be interested in a recent addition of `rpc/compose-full-import` that can do the import atomically (https://github.com/product-definition-center/product-definition-center/commit/b331eb64882e37404a486d45a8001af7eeb258e8). There are no messages sent yet, though.

**Comment by ralphbean** [comment]
Cool.  I'll a message to that here too if that's okay...

**Comment by ralphbean** [comment]
Nevermind.  After looking at it, the code for `rpc/compose-full-import` will invoke the code that creates the compose *and* generates the messages for the rpms and images import.  So, no need to add another message for it.

I'm :+1: to merge this as is.

**Comment by ralphbean** [comment]
This one seemed to be merge-able when I submitted it, but it looks like there's conflicts now.  Will rebase.

**Comment by ralphbean** [comment]
OK, rebased on master.

**Comment by simozhan** [comment]
:+1:

**Pull request merged**
