### PR TITLE
Remove permissions from inactive user accounts

### PR DESCRIPTION
**Pull request by ycheng-aa**
If a member is staff but not in any group other than
user group itself, set the user to inactive and remove
from all groups in PDC.

JIRA: PDC-1345

### CODE REVIEW

**Comment by lubomir** [comment]
Is it actually necessary to create a set of all active users? This could get really large.

Would it work the same if we just assumed that a user is inactive if it's not a service and LDAP does not return anything?

**Comment by ycheng-aa** [comment]
I am not sure about the meaning of *LDAP does not return anything* here. It looks LDAP will return the information of a group name and a list of corresponding users. Do you mean we can know directly whether a user is in a group except the user group itself?

**Comment by lubomir** [comment]
I meant this condition:
```
data = backends.get_ldap_user(conn, user.username)
if not data:
    # user not in LDAP
```

**Comment by ycheng-aa** [comment]
Fixed in 0771dc59b76. Thanks.

**Comment by bliuredhat** [comment]
looks good for me

**Comment by simozhan** [comment]
looks good

**Pull request merged**
