### PR TITLE
Delete App partners.

### PR DESCRIPTION
**Pull request by simozhan**
Remove tables and content type as well.

JIRA: PDC-1186

### CODE REVIEW

**Comment by bliuredhat** [comment]
:+1:

**Comment by lubomir** [comment]
Looks good to me. Would it make sense to move the script to `pdc/scripts/`?

**Comment by simozhan** [comment]
@lubomir yes. Moved it

**Comment by xychu** [comment]
:+1:

**Comment by bliuredhat** [comment]
:+1:

**Pull request closed without merging**
