### PR TITLE
Use single string field for user names.

### PR DESCRIPTION
**Pull request by ycheng-aa**
User single string instead of first name and last
name combination.

JIRA: PDC-1051

### CODE REVIEW

**Comment by bliuredhat** [comment]
+1

**Comment by lubomir** [comment]
The migration seems needlessly complicated: why not add new field, copy full name, remove old fields?

**Comment by ycheng-aa** [comment]
Good point. Fixed in d1dbad8ada10cb6. Thanks.

**Comment by lubomir** [comment]
:+1:

**Comment by xychu** [comment]
:+1:

**Pull request merged**
