### PR TITLE
Add pdc_endpoint in content format table

### PR DESCRIPTION
**Pull request by xiangge**
Add pdc_endpoint in content format table

JIRA: PDC-2362

### CODE REVIEW

**Comment by xiangge** [comment]
Base on Ren Yang's solution.
Endpoint 2. deliverable_content_type
```
{
id,
name:
pdc_endpoint.
}
```
This new endpoint is dup with the content format, so just need add a pdc_endpoint here.

**Comment by hluk** [comment]
> This new endpoint is dup with the content format, so just need add a pdc_endpoint here.

OK, but this should be used in PDC-1924, right?

Shouldn't "name" be foreign key to "content-delivery-content-formats"?

**Comment by xiangge** [comment]
`OK, but this should be used in PDC-1924, right?
`
Yes.
`Shouldn't "name" be foreign key to "content-delivery-content-formats"?`
In content-delivery-repo's api, it shows the name, so we can get it there, and it is unique in content-delivery-content-formats. So people can get content-delivery-content-formats' data by name.
I think this pdc_endpoint is designed for future, currently I didn't see the use case.

**Comment by hluk** [comment]
If the new API is not used why implement it now? I think it should be implemented and used in #502.

I still don't understand why to use string instead of foreign key to content format. Using the key makes the relation stronger and clearer.

**Comment by xiangge** [comment]
Here is one data in new release-files:
        ```
   {
            "id": 33,
            "build": null,
            "package": null,
            "file": null,
            "file_primary_key": 2,
            "repo": {
                "release_id": "rhel-6.7",
                "content_category": "binary",
                "shadow": false,
                "repo_family": "beta",
                "id": 19348,
                "name": "rhel-6-desktop-beta-isos__6Client__i386",
                "variant_uid": "Client",
                "product_id": 68,
                "service": "pulp",
                "arch": "i386",
                "content_format": "iso"
            },
            "released_date": null,
            "release_date": "2017-11-11",
            "created_at": "2017-10-31T03:26:27.220497Z",
            "updated_at": "2017-10-31T03:27:47.941642Z",
            "zero_day_release": false,
            "obsolete": false
        }
```

You can see there is a content_format in repo, the foreign key is content_format's id in repo.
So we don't need to add the content_format's foreign key here. 
Add this pdc_endpoint is more likely to store the endpoints name of each type in future.

**Comment by hluk** [comment]
The problem is that this API is not used anywhere - i.e. no need to keep it. I would expect the other PR to use `pdc_endpoint` to find correct data model.

**Comment by xiangge** [comment]
Yes, that makes sense, will close this pr.

**Comment by xiangge** [comment]
@hluk  I have discussed with Ren again for this part, then I think we should add this column here, we can list the pdc_endpoint in release_files data, then ct can get the endpoint name and do further things.

Like:

>        {
>             "id": 39,
>             "file_primary_key": 5,
>             "repo": {
>                 "release_id": "rhel-6.8",
>                 "content_category": "binary",
>                 "shadow": false,
>                 "repo_family": "beta",
>                 "id": 18378,
>                 "name": "rhel-6-desktop-beta-rpms__6Client__i386",
>                 "variant_uid": "Client",
>                 "product_id": 68,
>                 "service": "pulp",
>                 "arch": "i386",
>                 "content_format": {
>                     "name": "rpm",
>                     "pdc_endpoint": "rpms"
>                 }
>             },
>             "released_date": null,
>             "release_date": "2017-11-12",
>             "created_at": "2017-10-31T08:59:38.007696Z",
>             "updated_at": "2017-10-31T08:59:46.888620Z",
>             "zero_day_release": false,
>             "obsolete": false
>         }

**Comment by xiangge** [comment]
Close this pr, as I have added the codes in #502

**Pull request closed without merging**
