### PR TITLE
Fix the bug about "Manage Overrides" on release without compose

### PR DESCRIPTION
**Pull request by bliuredhat**
JIRA: PDC-1421

### CODE REVIEW

**Comment by lubomir** [comment]
This should fix it :+1:

**Comment by simozhan** [comment]
Looks good to me.

**Comment by ycheng-aa** [comment]
Looks good. 

Maybe add a test case  to cover it even better.

**Comment by bliuredhat** [comment]
@ycheng-aa ; you are right, I add the test case~.

**Pull request merged**
