### PR TITLE
Provide new resource for storing RTT test results of brew image builds

### PR DESCRIPTION
**Pull request by ycheng-aa**
1. Add new resource build-image-rtt-tests.
2. Creat and delete are not allowed.
3. Build image's default test result should be untested.
4. Only test result is allowed to be modified.
5. Share test result status with current compose test values.

JIRA: PDC-1205

### CODE REVIEW

**Comment by lubomir** [comment]
Is this internal or should it really go to upstream?

**Comment by ycheng-aa** [comment]
@sochotnicky  as @lubomir asked, should this be internal or upstream? Thanks.

**Comment by ycheng-aa** [comment]
Moved the function to ComposeAcceptanceTestingState in 6589539f4b3e951f95b. Thanks.

**Comment by sochotnicky** [comment]
@ycheng-aa This is actually described as "build-image-rtt-tests" so should be fine here. 
@ralphbean I assume storing test results for things like qcow2 or docker images is something Fedora is interested in as well

**Comment by xychu** [comment]
Looks good to me.

**Comment by ralphbean** [comment]
> I assume storing test results for things like qcow2 or docker images is something Fedora is interested in as well

Yes... although we're not there yet.  Our test framework, taskotron, will be running those tests and storing the results on their own.  It is conceivable and desirable that we would pull those tests results in and mirror them in PDC as well.

**Pull request closed without merging**
