### PR TITLE
Allow using mod_auth_oidc for remote user auth.

### PR DESCRIPTION
**Pull request by ralphbean**
We'd like to try this out in Fedora.

### CODE REVIEW

**Comment by puiterwijk** [comment]
Thank you very much for this patch.
This looks to be in line with what Fedora Infra is now deploying.

**Comment by ralphbean** [comment]
Following up here since it's been almost a year.  I know the dev team is busy with other priorities, but we would appreciate this one being looked at.

**Comment by simozhan** [comment]
I don't have environment to try it. but i think the code looks quite good to me.

**Comment by ycheng-aa** [comment]
Looks good.

**Comment by ralphbean** [comment]
Thank you!

**Pull request merged**
