### PR TITLE
Restrict djangorestframework's version

### PR DESCRIPTION
**Pull request by xiangge**
Restrict djangorestframework's version to include more error info.

### CODE REVIEW

**Comment by hluk** [comment]
What "error info" is that?

Are you sure `djangorestframework >= 3.2` is available on supported platforms?

**Comment by xiangge** [comment]
Yes, the version is ok, my local env and qe's env are now 3.2.5.
And also, when you update a data with -d {"aaa": ["1","2"]}, and you put a wrong type data like {“aaa”: "1"}, it will raise "Expected a list of items but got type \"unicode\" in 3.2.5, but in 3.1 there is no such error info, not clear.

**Comment by hluk** [comment]
I meant, whether there is package `django-rest-framework` for all supported platform. But I just noticed that this needs to be defined in [pdc.spec file](https://github.com/product-definition-center/product-definition-center/blob/ad808e85eebe5a667723af9907f33c78fde18993/pdc.spec#L17). Should that be updated too for consistency? And is it possible to use newer version of the package on rhel7 and others?

**Comment by xiangge** [comment]
Oh, yes,I think it's ok for all platforms, I also changed this file, thanks for remind that.

**Pull request merged**
