### PR TITLE
Make MultiValueRegexFilter could treat empty string or wrong regexp f…

### PR DESCRIPTION
**Pull request by ycheng-aa**
…ormat

JIRA: PDC-1285

### CODE REVIEW

**Comment by simozhan** [comment]
I tried https://pdc.engineering.redhat.com/rest_api/v1/releases/?release_id=%28%28
and https://pdc.engineering.redhat.com/rest_api/v1/releases/?release_id=
it seems the first one returns nothing and the second one returns all releases. 
This implementation changes the behaviour, i am just wondering why not to keep the behaviour.

**Comment by ycheng-aa** [comment]
@simozhan  I think it's because release_id in ReleaseFilter is not MultiValueFilter, and this filter is followed MultiValueFilter behavior. In MultiValueFilter it seems is this kind of behavior for release-component-contacts/?component=.  Please see the expected result part in https://bugzilla.redhat.com/show_bug.cgi?id=1302550

**Comment by simozhan** [comment]
@ycheng-aa so then the problem is for different api, the search behavior is different. i think we should make them consistent.

**Comment by ycheng-aa** [comment]
@simozhan Yes, it looks more reasonable. For this task itself I think just support regexp and follow previous behavior, just like QA expected. Make them consistent may should be in a separate task. But I am not sure if this kind of change will break some existing script.

**Comment by simozhan** [comment]
it looks good to me for this task and i am ok if there is another ticket to track the issue.

**Comment by bliuredhat** [comment]
looks good for me

**Pull request closed without merging**
