### PR TITLE
Remove productmd hacks, deserialize data directly.

### PR DESCRIPTION
**Pull request by dmach**

### CODE REVIEW

**Comment by lubomir** [comment]
Looks good to me. As discussed, doing the same thing with context manager would [look like this](https://gist.github.com/lubomir/721dd62b48c2bcf84443), but I don't think it is much better.

**Comment by ycheng-aa** [comment]
Looks good.

**Comment by simozhan** [comment]
:+1:

**Comment by lubomir** [comment]
Merged as 8d24893fffa.

**Pull request closed without merging**
