### PR TITLE
Merge release branch back to master

### PR DESCRIPTION
**Pull request by ycheng-aa**
After test is done and resolved the conflict.

### CODE REVIEW

**Comment by ycheng-aa** [comment]
@simozhan  It looks like in your commit "Drop old contact API.", you removed tests " GlobalComponentContactInfoRESTTestCase" and "ReleaseComponentContactInfoRESTTestCase". These 2 tests are for contacts we are using and should not be removed.And I also add a test in release branch.

After the release branch merged, I think the tests should be resotred.

**Comment by bliuredhat** [comment]
:+1:

**Comment by simozhan** [comment]
@ycheng-aa thanks. i moved GlobalComponentContactInfoRESTTestCase to GlobalComponentContactRESTTestCase and ReleaseComponentContactInfoRESTTestCase to ReleaseComponentContactRESTTestCase in contact app. There already exists ReleaseComponentContactRESTTestCase, probably some test cases in ReleaseComponentContactInfoRESTTestCase is masked.

**Comment by ycheng-aa** [comment]
Thanks @simozhan , I also moved my test to new place in 127d30cae7ca315. Please review.

**Comment by simozhan** [comment]
looks good to me

**Comment by xychu** [comment]
:+1:  please also merge the client release branch :-)

**Comment by ycheng-aa** [comment]
I merged release branch to master branch in internal and will do in this one. @bliuredhat will merge client release branch after qa passed.

**Pull request merged**
